### ISSUE TITLE
Custom floor plan from outline

### ISSUE THREAD

**Issue by MCrafterzz** [ranjian0/building_tools#125] opened 2020-06-14 08:03 UTC
**Is your feature request related to a problem? Please describe.**
Yes the current floorplan system only allows for a small amount of available shapes.

**Describe the solution you'd like**
Having a custom floorplan option where you can choose a object. Then it would create the floorplan from the other object's vertex outline. This way you can quickly create any shape!

The workflow:
- Create a new object
- Extrude vertices until you have you outline
- Create a new floorplan, change to custom and select the other object
- The tool converts it to a floorplan (also it may be a good idea to remove the outline object) with polygon triangulation? Or whatever is best in blender.

Why not do it manually?
- It can be quickly done manually by creating one big n-gon but this doesn't work for all shapes, also it's generally better to have multiple faces rather than one large n-gon.

There you go @ranjian0, rewritten from #124

**Comment by pearcemichal** [comment] 2020-06-27 22:46
To add to this, This technically works now, in that you are able to select a shape and add floors to it, however if you try and add windows or a roof blender hangs / crashes.

**Comment by luckykadam** [comment] 2020-06-28 07:21
@pearcemichal It should be working. Can you share more details of crash? blend file or stack trace(crash report).

**Comment by pearcemichal** [comment] 2020-06-28 13:32
I found the cause of the crash, it happens when the normals of the created surface are the wrong direction, which can often happen when creating a shape by connecting vertices together.

However there is still a hang when you try and add a roof.

1) select the mesh face
2) add floor (if you flip the normals of the face before doing this, blender crashes)
3) click the top face
4) add roof 

blender will hang and eventually stop responding and need to be closed. 

[building_tools_test.zip](https://github.com/ranjian0/building_tool/files/4842319/building_tools_test.zip)

**Comment by ranjian0** [comment] 2020-06-28 14:33
Are you using the release version or from `master` branch? The roof issue was closed in #135 but it is not available in release version.

**Closed** 2020-08-01 11:47 UTC
Labels: Medium Priority, enhancement
